image: mhart/alpine-node:6.10.0

stages:
    - test
    - build

test:
    script:
        - npm i
        - npm test
    artifacts:
        paths:
            - coverage

build:
    script:
        - npm run build
    artifacts:
        paths:
            - dist
    only:
       - master