image: mhart/alpine-node:6.10.0

stages:
    - test
    - build

test:
    stage: test
    script:
        - npm i
        - npm test
    artifacts:
        paths:
            - coverage
    except:
      - master

build:
    stage: build
    script:
        - npm i
        - npm test
        - npm run build
    artifacts:
        paths:
            - coverage
            - dist
    only:
       - master
