language: node_js
node_js:
  - "6"
before_install:
  - npm i npm@3.10.10 -g
install:
  - npm i
script:
  - npm test
  - npm run build
cache:
  directories:
    - "node_modules"
branches:
  only:
    - master