language: node_js
node_js:
- '6'
before_install:
- npm i npm@3.10.10 -g
install:
- npm i
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- npm test
- npm run build
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
cache:
  directories:
  - node_modules
branches:
  only:
  - master
env:
  global:
  - secure: ct3eBSDMCYSxS8keS6cAiinHwqeYzyQfBzlqFsYis3terGJ9OQA13QReWsSoxKxgJTsaSrgz1b29jSUbjdS3YgVtnsU5+kt1JcaBiCCKhBQVn9MN6+7vrEOrKTQrait2CP2ys+aO2CaK73LA5aIXImq5pP+OrYxMZoEIRRSmEbM0wHni0YYmfrIn7SzKmUozJhmLu6Ty7+BYrZicTQs6rDLLIorwM4D7IPb2Um3eqM4ti50oklFfa5NQYHoznrSYHFyCjPeiNbr1MBcM1OWkbFUDvKdo1QBPl6vdJJzzgB/c4JJnZsEWBDVoMrRXKsEzC4GPDOmcDjlHWssd4dIlMqs1GVufcu0GTeqGCxn3QNC5Ut86qG9sci9XYDygam/N3c4TWoSjdT1//BetNbsJmBJ5c+i5rOWtd8sYTxmYoIb5Sc/7KC3Av+8GLYCT48eIf6f70Lo3f3dkU2SSIHrxirDkzBhVqnddPCu4qAb+kImxxmsq5N/otn7aoEwuqBiB2VhemVl5L8KlGiZniN8G6e0S7oY6u8k1vtpMFe8MtrRdWIewOzLE1PoBc7BLxrOhX8KcwiSrA3bkhSJ4G+PgvJRxYnSgVHC7A/dkJ0N2JrH3punyGbe04W1VJG04ghgz6GOySju6komsXgw3Hd/B72KDtizsaUT8sle69f8kNm8=
  - secure: Vqm79YIUcSQAzFPhIeZJIr5UPRKiLlwO5YkNSQRJ5L53G65EXziS+TQcPJHS7y/IUx/QZxWRsyeHC49ouvLDBzL27ukqqBS5o2EtS3Xr0Ev4V70RipdiWWwayvviw1TVPYbGVFcYObyeVnZb2oieJeMheARLpehVzxDXbMoYGzJ9n+NVLeLADMF/RrukQFeERWxjCqD3MVE4AsdVjdXfuPVDxZ5fusp45TTtBCTiOFog2Q5/+WJJPV+wouCRzMBODWWtgO4Jtba9fRwejxX/Ghfc2sJ5XaWKJtTx+Bj2G12W6xHUmMTmMsGCdr8hdChXFcXv8xapuqo1whnBn3yfU26ucN9LId0/0IdN5Vjeh8Ge7n8mNxkGr3fww2LQVRnlGRthwdJpAmcyIdYiWNb3kuJN+oms39xT8ueMzvX8JtP36Kh2Qq5qGnxqjlOt0XKoVe12DYe+5reBE3CziAsRMluL8z9soNZX6887jTuTKML4gA0sm8VDXiABjl0vvSk7A0qgDFmbTeSId0Do7cyTqE13qPujUHZl2okw9C//uFWnaL1vrzrHOxQQT1/j8EVeTqaT3Nh1lhT95BbXXpcdFrphlv6Y3517DUDoWkBc+V3H3W8nrPMc9WUO4T4CfBUz53FjSPP+nQsWHMXhOB32OahRxKuNo9dbn+4JtZ5WWR4=
