language: node_js
node_js:
  - "8"
before_install:
  - npm i npm@latest -g
install:
  - npm i
script:
  - npm test
  - npm run build
cache:
  directories:
    - "node_modules"
branches:
  only:
    - master